name: Build and Run Tests

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build Core
      run: dotnet build "src\DarkMusicConcepts\DarkMusicConcepts.csproj"      
    - name: Build Units
      run: dotnet build "src\DarkMusicConcepts.Units\DarkMusicConcepts.Units.csproj"
    - name: Build Tests
      run: dotnet build "tests\DarkMusicConcepts.Tests\DarkMusicConcepts.Tests.csproj"
    - name: Run Tests
      run: dotnet test --no-build "tests\DarkMusicConcepts.Tests\DarkMusicConcepts.Tests.csproj"
